---
- name: Create .kube directories
  ansible.builtin.file:
    path: "~{{ item }}/.kube"
    state: directory
    owner: "{{ item }}"
    mode: "0700"
  loop: "{{ control_plane_kubeconfig_users }}"

- name: Copy the admin kubeconfig to users
  ansible.builtin.copy:
    src: "{{ control_plane_admin_kubeconfig }}"
    remote_src: true
    dest: "~{{ item }}/.kube/config"
    owner: "{{ item }}"
    mode: "0600"
  loop: "{{ control_plane_kubeconfig_users }}"
